### ISSUE TITLE
Override to use react-query's useQuery for operationId with POST method

### ISSUE THREAD

**Issue by wan54** [anymaniax/orval#198]
Hi,

Thank you for making this awesome library.

This is a more of question for react-query generator...

I wonder if it's already supported to override an operationId with POST method so that `useQuery` is generated instead of `useMutation`? I have a search endpoint that needs to use POST method to support complex filters that needs to be passed in the request body and other parameters in the query parameter.

I have tried the following in the config but still generating `useMutation`

```
output: {
  override: {
    operations: {
      searchSomething: {
        query: {
          useQuery: true
        }
      }  
    }
  }
}
```

`searchSomething` operationId uses POST method

**Comment by anymaniax** [comment]
Hello @wan54, it's not possible to do that but I will add that feature for the next big release. It will work the way you did it.

**Comment by anymaniax** [comment]
Added with the `6.0.0`. You can try it now with `orval@next`

**Comment by anymaniax** [comment]
I close the issue leave me a comment if you have any problem

**Comment by ristomatti** [comment]
@anymaniax Sorry to comment to a closed issue but how should this be used? I'd ideally like to be able to create `useQuery` hooks for most of the POST request defined on this OpenAPI spec blob:https://docs.loop54.com/b5eb970e-e55e-4182-8bf9-e425722a111c found from Loop54's [documentation](https://docs.loop54.com/latest/api/docs.html).

Mainly I'm interested in the ones tagged "user initiated" none of which are actual mutations but accessed via POST requests due to potentially complex parameters, as was the issue with the original reporter of this issue. Since I was not able to get this working as a "global" config, I tried going with a single operation, like this:

```ts
export default defineConfig({
  loop54: {
    input: {
      target: './schema/loop54-openapi.json',
    },
    output: {
      workspace: `./src/lib/api/loop54`,
      target: `./loop54.ts`,
      schemas: './models',
      client: 'axios-functions',
      mode: 'split',
      clean: true,
      mock: false,
      override: {
        requestOptions: false,
        operations: {
          postSearch: {
            query: {
              useQuery: true,
            },
          },
        },
      },
    }
  }
});
```

The resulted output:

```ts
/**
 * Used for performing search requests to the engine.
 * @summary Perform a search request
 */
export const postSearch = async (
  searchRequest: SearchRequest
): Promise<AxiosResponse<SearchResponse>> => {
  return axios.post(`/search`, searchRequest, {});
};

export type PostSearchMutationResult = NonNullable<AsyncReturnType<typeof postSearch>>;
export type PostSearchMutationBody = SearchRequest;
export type PostSearchMutationError = AxiosError<ErrorDetails>;

export const usePostSearch = <TError = AxiosError<ErrorDetails>, TContext = unknown>(
  mutationOptions?: UseMutationOptions<
    AsyncReturnType<typeof postSearch>,
    TError,
    { data: SearchRequest },
    TContext
  >
) => {
  const mutationFn: MutationFunction<
    AsyncReturnType<typeof postSearch>,
    { data: SearchRequest }
  > = async (props) => {
    const { data } = props || {};

    return postSearch(data);
  };

  return useMutation<AsyncReturnType<typeof postSearch>, TError, { data: SearchRequest }, TContext>(
    mutationFn,
    mutationOptions
  );
};
```

I'm wondering if there's something weird going on with the API spec causing this as a side effect, as I first had to remove a missing references within it. I've created a gist with the modified version I am actually using: https://gist.github.com/ristomatti/452bd461b05fdf5e21c4c63dbb206b67

Orval has been such a huge help even with just using the generated Axios requests but it still seems a shame to not use this feature since it obviously is there. :)

**Comment by anymaniax** [comment]
Hello @ristomatti, is it normal that your output is react query code and the client is still axios-functions. If you want to generate react query code you need to put the react query client
