### ISSUE TITLE
Support for remote OpenAPI Spec?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [anymaniax/orval#601]
Question:

Are remote links supported for the configuration setting associated with the input file? i.e., can I use https://something?

**Comment by anymaniax** [comment]
@mfreeman-xtivia normally yes

**Comment by mfreeman-xtivia** [comment]
"normally yes"?

meaning sometimes I can't?

**Comment by anymaniax** [comment]
Dépend of the data ta you return. Need to be a json format or directly à specification file

**Comment by anymaniax** [comment]
To be more precise behind it use [this](https://github.com/APIDevTools/swagger-parser/blob/main/docs/swagger-parser.md#resolveapi-options-callback). You can also pass your own parser. You check the doc [here](https://orval.dev/reference/configuration/input#parseroptions). I was saying normally yes because depending of your setup I pretty sure it doesn’t handle every case
