### ISSUE TITLE
output.mock = true does not handle circular references causing timeout

### ISSUE THREAD

**Issue by mwillbanks** [anymaniax/orval#764]
## What are the steps to reproduce this issue?

1. Create an OpenAPI spec with circular references
2. Utilize similar configuration to the following:
```typescript
export default defineConfig({
  myProject: {
    input: './openapi.yaml',
    output: {
      client: 'react-query',
      headers: true,
      mock: true, // mocks are not properly handling circular references in the schema
      packageJson: './package.json',
      prettier: true,
      target: './src/api.ts',
      workspace: './myProject-sdk',
    }
  }
});
```
3. Set the configuration to output msw mocks

## What happens?

Process hangs and never completes:

```
/Volumes/Projects/sg-api main* ❯ DEBUG=* npx orval                                                                                                                      02:18:35
🍻 Start orval v6.11.1 - A swagger client generator for typescript
  orval:file-load bundled file loaded in 26ms +0ms
  orval:file-load bundled file loaded in 9ms +175ms
^C
```

## What were you expecting to happen?

Generates as normal.

```
main* ❯ npx orval                                                                                                                              02:22:25
🍻 Start orval v6.11.1 - A swagger client generator for typescript
🎉 myProject - Your OpenAPI spec has been converted into ready to use orval!
```

## Any logs, error output, etc?

Unfortunately, it appears that orval doesn't really support the regular debug module, I've taken a quick look at the msw generator but I did not find anything specific in my quick view through it.

## Any other comments?

…

## What versions are you using?

**Operating System:** macOS Ventura 13.1 (22C65)
**Package Version:** 6.11.1
**Browser Version:** n/a

**Comment by mwillbanks** [comment]
It appears that this is attempted to be handled via: https://github.com/anymaniax/orval/blob/master/packages/msw/src/mocks.ts#L142

Although, what could very well likely be the case is that the circular reference is not specific to the original schema or ultimately creates a circular reference elsewhere.  Since swagger-parser is being used under the hoods, I would expect that we would be looking at the circular references themselves https://apitools.dev/swagger-parser/docs/#circular-refs

since there is not really any debug methods put throughout the codebase it's hard to track specifically what caused it within our models, however, we often have models which can link back to various depths for instance:

organization -> users (array of users) -> organizations (array of organizations) -> users (array of users) and so on and so forth. none of these are actually marked as required in the base type to attempt to prevent circular relation issues but it certainly is providing a root cause for what is causing msw to not generate.

**Comment by arlyon** [comment]
There are two things that can help this. The first, is that orval just spits out arbitrarily nested schemas rather than attempting to reuse / encapsulate. Ideally, each schema would have a function generated which is responsible for building the appropriate object at runtime, and schemas that refer to others could use reuse those functions. This would reduce the amount of code generated by about 90% in my case and at least fixes the codegen-time hang but obviously on its own would not prevent runtime stack overflow.

I think to fix this we could fairly easily have the schema functions take some parameters to limit opt-in to potentially recursive schemas which orval would use in essentially the same way as it does now at codegen-time.

**Comment by anymaniax** [comment]
Hello guys, it’s a great idea @arlyon. Do you have time to work on it?

**Comment by arlyon** [comment]
Yes. I will need to make some changes to the way the mocks are generated, though. I plan on transforming it into two stages rather than serializing on the fly. The first stage is transforms the definition into some intermediary format which we can apply transformations to, then the second does a fairly trivial serialization step (100 loc or so) that converts this AST into the final code. I am currently in the process of deferring the selialization and will then be able to do things like sorting keys afterwards.

**Comment by melloware** [comment]
@Will-Mann-16 does your new fix, fix this also?

**Comment by Will-Mann-16** [comment]
It does yes.

**Comment by AndrewChubatiuk** [comment]
@melloware 
this issue reproduces when $ref name contains dots in a part after a last slash, like
`https://raw.githubusercontent.com/argoproj/argo-workflows/v3.4.5/api/openapi-spec/swagger.json#/definitions/io.argoproj.workflow.v1alpha1.WorkflowTemplateList`

current approach stores in a list of refs value `IoArgoprojWorkflowV1alpha1WorkflowTemplateList` and uses `io.argoproj.workflow.v1alpha1.WorkflowTemplateList` to check

**Comment by melloware** [comment]
@AndrewChubatiuk can you open a new ticket with your reproducer.
