### ISSUE TITLE
SWR: Duplicate identifier 'query'

### ISSUE THREAD

**Issue by majkl-zumberi** [anymaniax/orval#800]
i have an api that request as parameter `query`

since query in the generated useSwr already exist as constant it's conflicting

`export const getResponsesControllerSearchResponsesKey = (query: string,) => [`/api/v1/responses/search/${query}`];`

```
export const useResponsesControllerSearchResponses = <TError = unknown>(
 query: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof responsesControllerSearchResponses>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }

  ) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(query)
    const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getResponsesControllerSearchResponsesKey(query) : null);
  const swrFn = () => responsesControllerSearchResponses(query, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
```

**Comment by AffeJonsson** [comment]
I'm having the exact same problem. I've tried renaming the parameter in the output.override.transformer part of the config, but it's really wonky and doesn't work properly. Unsure how to solve this correctly?

**Comment by AffeJonsson** [comment]
I "solved" it by doing a find-and-replace using a different package that is ran in the generated files containing the hooks:
  ```
from: /const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(.+)\s+return {\s+swrKey,\s+\.\.\.query,\s+}/g,
  to: "const _query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>$1\n\nreturn {\nswrKey,\n..._query,\n}",
```

Not ideal, but works for now. Best would be if the generated variable names that are not exposed outside the file would get a more distinct name than `query`. Maybe something like `___query`  would be good enough?

**Comment by soartec-lab** [comment]
I have considered several ways to deal with this problem:

1. Define variable names used in generated functions as reserved words and perform input validate before generating source code.

    Providing an input check will increase the overhead in executing the source code generation process.

2. If you do not want to change the name of the parameter used in the `OpenAPI` definition, change the name of the function argument output by `transformer`.

    Although it can be used as is, it will be inconvenient as users will have to understand this problem before implementing the function.

3. As suggested, add a `_` prefix to all variable names in functions so that they do not affect the input OpenAPI definition.

    All variable names in automatically generated functions must be updated. The scope of impact is large, but it is possible. Users who encounter this problem will be saved

---

@melloware 

Hi, Please check the above countermeasures.

3 is the most effective, but you will have to be careful about variable names in functions in all future developments. Also, in the first place, if an unintended name such as `query` is given to a parameter name, I think it would be a good idea to ask the user to make their own judgment and avoid it.

I think you can either deal with 3 based on these, or close this issue if it is unnecessary.

What do you think?

**Comment by melloware** [comment]
I think 3 makes the most sense. If they are param values.

**Comment by soartec-lab** [comment]
@melloware 
Ok, I'll handle this, so could you assign this issue to me?

**Comment by soartec-lab** [comment]
fix by https://github.com/anymaniax/orval/pull/1130

**Comment by melloware** [comment]
Excellent I assigned you the ticket and made one code review comment.
